"""
Tests for TASK-3.7 — Public blog reader + SEO endpoints.

Test cases:
  test_list_returns_only_published         — GET /api/blog/ returns only is_published=True
  test_list_excludes_unpublished           — unpublished articles not in list
  test_list_ordered_newest_first           — results sorted by published_at DESC
  test_list_includes_is_ai_enhanced_flag   — is_ai_enhanced = True when published_version='cleaned'
  test_detail_returns_body_html            — GET /api/blog/{slug} returns full body_html
  test_detail_404_unknown_slug             — 404 for non-existent slug
  test_detail_404_unpublished_article      — 404 if article exists but not published
  test_resolve_body_uses_cleaned_version   — unit test: returns body_html_cleaned when approved
  test_resolve_body_uses_original_version  — unit test: returns content when not approved
  test_resolve_body_cleaned_missing        — unit test: falls back to content if cleaned is None

Pattern: self-contained (create articles directly in DB → test → cleanup).
No auth required — blog endpoints are fully public.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from types import SimpleNamespace

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from sqlalchemy import text

from app.core.database import AsyncSessionLocal
from app.main import app
from app.routers.blog import _resolve_body


# ── Helper ────────────────────────────────────────────────────────────────────


async def _create_article(
    *,
    slug: str,
    title: str,
    content: str = "<p>Corps original.</p>",
    body_html_cleaned: str | None = None,
    published_version: str = "original",
    is_published: bool = True,
    published_at: datetime | None = None,
) -> SimpleNamespace:
    """
    Insert a BlogArticle via raw SQL, bypassing the ORM.

    WHY raw SQL: the BlogArticle model has a pgvector `embedding` column.
    SQLAlchemy cannot send None for a vector column via the asyncpg dialect
    (DatatypeMismatchError). Raw SQL lets us omit the column entirely so
    the DB default (NULL) applies.

    Args:
        slug:              URL-safe slug (embed a uuid fragment for uniqueness).
        title:             Article title.
        content:           Original HTML body.
        body_html_cleaned: AI-cleaned version (optional).
        published_version: "original" or "cleaned".
        is_published:      Whether the article is visible publicly.
        published_at:      Publication datetime (defaults to now).

    Returns:
        SimpleNamespace with .slug, .title, .is_published attributes.
    """
    effective_at = published_at or datetime.now(timezone.utc)
    async with AsyncSessionLocal() as db:
        await db.execute(
            text("""
                INSERT INTO blog_articles
                    (id, slug, title, content, body_html_cleaned,
                     published_version, is_published, published_at, excerpt)
                VALUES
                    (:id, :slug, :title, :content, :body_html_cleaned,
                     :published_version, :is_published, :published_at, :excerpt)
            """),
            {
                "id": str(uuid.uuid4()),
                "slug": slug,
                "title": title,
                "content": content,
                "body_html_cleaned": body_html_cleaned,
                "published_version": published_version,
                "is_published": is_published,
                "published_at": effective_at,
                "excerpt": f"Extrait de {title}",
            },
        )
        await db.commit()

    return SimpleNamespace(slug=slug, title=title, is_published=is_published)


async def _cleanup_articles(slugs: list[str]) -> None:
    """Remove test articles by slug to keep the DB clean."""
    if not slugs:
        return
    # Use string formatting — safe because slugs are generated by test code.
    placeholders = ", ".join(f"'{s}'" for s in slugs)
    async with AsyncSessionLocal() as db:
        await db.execute(text(f"DELETE FROM blog_articles WHERE slug IN ({placeholders})"))
        await db.commit()


# ── Fixtures ──────────────────────────────────────────────────────────────────
# WHY no async db fixtures: pytest_asyncio fixtures run teardown in a
# function-scoped loop but asyncpg connections are on the session-scoped loop,
# causing "Future attached to a different loop" errors. All setup/teardown is
# done inline with try/finally per LEARNINGS.md convention.

_RUN_ID = uuid.uuid4().hex[:8]


@pytest_asyncio.fixture()
async def client():
    """Unauthenticated HTTPX client (blog endpoints are public)."""
    async with AsyncClient(
        transport=ASGITransport(app=app),
        base_url="http://test",
    ) as c:
        yield c


# ── Tests: list endpoint ──────────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_list_returns_only_published(client):
    """
    GET /api/blog/ must return at least the published article and NOT
    include the unpublished one.
    """
    pub_slug = f"pub-list-{_RUN_ID}"
    draft_slug = f"draft-list-{_RUN_ID}"
    try:
        await _create_article(slug=pub_slug, title="Article publié", is_published=True)
        await _create_article(slug=draft_slug, title="Brouillon liste", is_published=False)

        resp = await client.get("/api/blog/")
        assert resp.status_code == 200

        slugs = [a["slug"] for a in resp.json()]
        assert pub_slug in slugs
        assert draft_slug not in slugs
    finally:
        await _cleanup_articles([pub_slug, draft_slug])


@pytest.mark.asyncio
async def test_list_excludes_unpublished(client):
    """
    Unpublished articles must NEVER appear in GET /api/blog/.
    """
    slug = f"draft-excl-{_RUN_ID}"
    try:
        await _create_article(slug=slug, title="Brouillon exclusion", is_published=False)

        resp = await client.get("/api/blog/")
        assert resp.status_code == 200

        slugs = [a["slug"] for a in resp.json()]
        assert slug not in slugs
    finally:
        await _cleanup_articles([slug])


@pytest.mark.asyncio
async def test_list_ordered_newest_first(client):
    """
    Results should be sorted by published_at DESC (newest first).
    We create two articles with known timestamps and verify ordering.
    """
    slug_old = f"old-{_RUN_ID}"
    slug_new = f"new-{_RUN_ID}"
    try:
        await _create_article(
            slug=slug_old,
            title="Vieil article",
            published_at=datetime(2024, 1, 1, tzinfo=timezone.utc),
        )
        await _create_article(
            slug=slug_new,
            title="Nouvel article",
            published_at=datetime(2025, 6, 1, tzinfo=timezone.utc),
        )

        resp = await client.get("/api/blog/")
        assert resp.status_code == 200

        articles = resp.json()
        slugs = [a["slug"] for a in articles]

        # Both test articles must be present
        assert slug_new in slugs
        assert slug_old in slugs

        # Newer must come BEFORE older
        assert slugs.index(slug_new) < slugs.index(slug_old)
    finally:
        await _cleanup_articles([slug_old, slug_new])


@pytest.mark.asyncio
async def test_list_includes_is_ai_enhanced_flag(client):
    """
    is_ai_enhanced must be True when published_version == 'cleaned'.
    """
    slug = f"ai-enhanced-{_RUN_ID}"
    try:
        await _create_article(
            slug=slug,
            title="Article amélioré IA",
            body_html_cleaned="<p>Version nettoyée.</p>",
            published_version="cleaned",
        )

        resp = await client.get("/api/blog/")
        assert resp.status_code == 200

        article = next((a for a in resp.json() if a["slug"] == slug), None)
        assert article is not None
        assert article["is_ai_enhanced"] is True
    finally:
        await _cleanup_articles([slug])


@pytest.mark.asyncio
async def test_list_not_ai_enhanced_for_original(client):
    """
    is_ai_enhanced must be False when published_version == 'original'.
    """
    slug = f"original-{_RUN_ID}"
    try:
        await _create_article(
            slug=slug,
            title="Article non amélioré",
            published_version="original",
        )

        resp = await client.get("/api/blog/")
        assert resp.status_code == 200

        article = next((a for a in resp.json() if a["slug"] == slug), None)
        assert article is not None
        assert article["is_ai_enhanced"] is False
    finally:
        await _cleanup_articles([slug])


# ── Tests: detail endpoint ────────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_detail_returns_body_html(client):
    """
    GET /api/blog/{slug} must return body_html for a published article.
    """
    slug = f"detail-body-{_RUN_ID}"
    try:
        article = await _create_article(
            slug=slug,
            title="Article corps",
            content="<p>Corps de test.</p>",
            is_published=True,
        )

        resp = await client.get(f"/api/blog/{article.slug}")
        assert resp.status_code == 200

        data = resp.json()
        assert data["slug"] == article.slug
        assert data["title"] == article.title
        assert "body_html" in data
        assert len(data["body_html"]) > 0
    finally:
        await _cleanup_articles([slug])


@pytest.mark.asyncio
async def test_detail_404_unknown_slug(client):
    """
    GET /api/blog/nonexistent-slug must return 404.
    """
    resp = await client.get(f"/api/blog/this-slug-does-not-exist-{_RUN_ID}")
    assert resp.status_code == 404


@pytest.mark.asyncio
async def test_detail_404_unpublished_article(client):
    """
    GET /api/blog/{slug} must return 404 if article is not published —
    even if the article exists in the DB.
    """
    slug = f"unpub-detail-{_RUN_ID}"
    try:
        article = await _create_article(slug=slug, title="Draft detail", is_published=False)

        resp = await client.get(f"/api/blog/{article.slug}")
        assert resp.status_code == 404
    finally:
        await _cleanup_articles([slug])


@pytest.mark.asyncio
async def test_detail_serves_cleaned_version(client):
    """
    When published_version == 'cleaned' and body_html_cleaned is set,
    GET /api/blog/{slug} must return body_html_cleaned as body_html.
    """
    slug = f"cleaned-detail-{_RUN_ID}"
    try:
        await _create_article(
            slug=slug,
            title="Article version nettoyée",
            content="<p>Version originale.</p>",
            body_html_cleaned="<p>Version améliorée par IA.</p>",
            published_version="cleaned",
        )

        resp = await client.get(f"/api/blog/{slug}")
        assert resp.status_code == 200
        assert resp.json()["body_html"] == "<p>Version améliorée par IA.</p>"
    finally:
        await _cleanup_articles([slug])


@pytest.mark.asyncio
async def test_detail_serves_original_when_not_cleaned(client):
    """
    When published_version == 'original', GET /api/blog/{slug} must return
    the original content as body_html — even if body_html_cleaned exists.
    """
    slug = f"original-detail-{_RUN_ID}"
    try:
        await _create_article(
            slug=slug,
            title="Article version originale",
            content="<p>Version originale.</p>",
            body_html_cleaned="<p>IA version (not published).</p>",
            published_version="original",
        )

        resp = await client.get(f"/api/blog/{slug}")
        assert resp.status_code == 200
        assert resp.json()["body_html"] == "<p>Version originale.</p>"
    finally:
        await _cleanup_articles([slug])


# ── Unit tests: _resolve_body helper ─────────────────────────────────────────


def _make_article(
    *,
    content: str | None = "<p>original</p>",
    body_html_cleaned: str | None = None,
    published_version: str = "original",
) -> SimpleNamespace:
    """
    Build a lightweight object for unit-testing _resolve_body.

    WHY SimpleNamespace not BlogArticle: BlogArticle.__new__() bypasses
    SQLAlchemy's mapper instrumentation, causing AttributeError when setting
    attributes. SimpleNamespace is sufficient because _resolve_body only reads
    .content, .body_html_cleaned, .published_version.

    Args:
        content:            Original HTML.
        body_html_cleaned:  AI-cleaned HTML (optional).
        published_version:  "original" or "cleaned".

    Returns:
        SimpleNamespace with the three attributes _resolve_body reads.
    """
    return SimpleNamespace(
        content=content,
        body_html_cleaned=body_html_cleaned,
        published_version=published_version,
    )


def test_resolve_body_uses_cleaned_version():
    """
    _resolve_body must return body_html_cleaned when published_version == 'cleaned'
    and body_html_cleaned is not None/empty.
    """
    article = _make_article(
        content="<p>original</p>",
        body_html_cleaned="<p>cleaned</p>",
        published_version="cleaned",
    )
    assert _resolve_body(article) == "<p>cleaned</p>"


def test_resolve_body_uses_original_version():
    """
    _resolve_body must return content when published_version == 'original'.
    """
    article = _make_article(
        content="<p>original</p>",
        body_html_cleaned="<p>cleaned</p>",
        published_version="original",
    )
    assert _resolve_body(article) == "<p>original</p>"


def test_resolve_body_cleaned_missing_falls_back():
    """
    _resolve_body must fall back to content when published_version == 'cleaned'
    but body_html_cleaned is None (e.g. enhancement failed).
    """
    article = _make_article(
        content="<p>original fallback</p>",
        body_html_cleaned=None,
        published_version="cleaned",
    )
    assert _resolve_body(article) == "<p>original fallback</p>"


def test_resolve_body_empty_content_returns_empty_string():
    """
    _resolve_body must return '' (not None) when content is None.
    """
    article = _make_article(
        content=None,   # type: ignore[arg-type]
        body_html_cleaned=None,
        published_version="original",
    )
    assert _resolve_body(article) == ""
