"""001_initial_schema

Revision ID: 162f9108f0d4
Revises: 
Create Date: 2026-04-10 20:55:50.517754+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '162f9108f0d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension — required for blog_articles.embedding column
    # pgvector/pgvector:pg16 image includes this extension, just needs enabling
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('expense_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('i18n_key', sa.String(length=100), nullable=False),
    sa.Column('percent_ca_repere', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('percent_ca_ideal', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('i18n_key')
    )
    op.create_table('partners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_category'), 'partners', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('preferred_tools', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('blog_articles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_articles_author_id'), 'blog_articles', ['author_id'], unique=False)
    op.create_index(op.f('ix_blog_articles_slug'), 'blog_articles', ['slug'], unique=True)
    # Convert embedding column from TEXT to vector(1024) for pgvector RAG
    # All existing values are NULL so the cast is safe
    op.execute("ALTER TABLE blog_articles ALTER COLUMN embedding TYPE vector(1024) USING embedding::vector;")
    op.create_table('coco_user_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_goals', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('profile_notes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('last_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('salons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('ville', sa.String(length=255), nullable=True),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('nb_employees', sa.Integer(), server_default='0', nullable=False),
    sa.Column('versement_liberatoire', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('acre', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fiscal_year_start', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salons_user_id'), 'salons', ['user_id'], unique=False)
    op.create_table('coco_conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('screen_context', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coco_conversations_salon_id'), 'coco_conversations', ['salon_id'], unique=False)
    op.create_index(op.f('ix_coco_conversations_user_id'), 'coco_conversations', ['user_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('hours_per_week', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weeks_per_year', sa.Numeric(precision=5, scale=2), server_default='45.6', nullable=False),
    sa.Column('salary_brut', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cotisations_patronales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('taux_occupation', sa.Numeric(precision=5, scale=4), server_default='0.65', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_salon_id'), 'employees', ['salon_id'], unique=False)
    op.create_table('monthly_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('ca_realise_ttc', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('subventions', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_month_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_month_id'], ['monthly_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_id', 'year', 'month', name='uq_monthly_report_salon_year_month')
    )
    op.create_index(op.f('ix_monthly_reports_salon_id'), 'monthly_reports', ['salon_id'], unique=False)
    op.create_table('noly_subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_id')
    )
    op.create_table('payslip_wallet',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('balance_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_id')
    )
    op.create_table('prime_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('prime_percent', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prime_config_salon_id'), 'prime_config', ['salon_id'], unique=False)
    op.create_table('salon_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('jours_ouverture_semaine', sa.Numeric(precision=3, scale=1), server_default='5', nullable=False),
    sa.Column('semaines_ouverture_an', sa.Numeric(precision=5, scale=1), server_default='45.6', nullable=False),
    sa.Column('heures_ouverture_jour', sa.Numeric(precision=4, scale=1), server_default='10', nullable=False),
    sa.Column('majoration_securite_benefice', sa.Numeric(precision=5, scale=4), server_default='0.10', nullable=False),
    sa.Column('taux_produits', sa.Numeric(precision=5, scale=4), server_default='0.10', nullable=False),
    sa.Column('taux_charges_fixes', sa.Numeric(precision=5, scale=4), server_default='0.25', nullable=False),
    sa.Column('percent_clients_f', sa.Numeric(precision=5, scale=4), server_default='0.80', nullable=False),
    sa.Column('montant_moyen_f', sa.Numeric(precision=12, scale=2), server_default='65', nullable=False),
    sa.Column('percent_clients_h', sa.Numeric(precision=5, scale=4), server_default='0.20', nullable=False),
    sa.Column('montant_moyen_h', sa.Numeric(precision=12, scale=2), server_default='30', nullable=False),
    sa.Column('nb_visites_moyen_f', sa.Numeric(precision=5, scale=1), server_default='4.2', nullable=False),
    sa.Column('nb_visites_moyen_h', sa.Numeric(precision=5, scale=1), server_default='6.6', nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salon_config_salon_id'), 'salon_config', ['salon_id'], unique=True)
    op.create_table('services',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('addon_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('prix_vente_ttc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prix_seuil_rentabilite', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prix_recommande', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_salon_id'), 'services', ['salon_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('monthly_report_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('amount_ttc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_ht', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tva_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['monthly_report_id'], ['monthly_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_monthly_report_id'), 'expenses', ['monthly_report_id'], unique=False)
    op.create_table('monthly_primes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('days_worked', sa.Integer(), nullable=False),
    sa.Column('objectif_initial', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deficit_anterieur', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('objectif_final', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resultat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ecart', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prime_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_primes_employee_id'), 'monthly_primes', ['employee_id'], unique=False)
    op.create_index(op.f('ix_monthly_primes_salon_id'), 'monthly_primes', ['salon_id'], unique=False)
    op.create_table('monthly_salaries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('monthly_report_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('salaire_net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cotisations_sociales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('days_worked', sa.Integer(), nullable=True),
    sa.Column('ca_realise', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monthly_report_id'], ['monthly_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_salaries_employee_id'), 'monthly_salaries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_monthly_salaries_monthly_report_id'), 'monthly_salaries', ['monthly_report_id'], unique=False)
    op.create_table('payslip_forms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('prime_conventionnelle_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ca_services_ht', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prime_revente_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ca_revente_ht', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('absence_conges_du', sa.Date(), nullable=True),
    sa.Column('absence_conges_au', sa.Date(), nullable=True),
    sa.Column('absence_maladie_du', sa.Date(), nullable=True),
    sa.Column('absence_maladie_au', sa.Date(), nullable=True),
    sa.Column('absence_injustifiee_du', sa.Date(), nullable=True),
    sa.Column('absence_injustifiee_au', sa.Date(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_forms_employee_id'), 'payslip_forms', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslip_forms_salon_id'), 'payslip_forms', ['salon_id'], unique=False)
    op.create_table('payslip_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('payslip_form_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payslip_form_id'], ['payslip_forms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['payslip_wallet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_transactions_wallet_id'), 'payslip_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payslip_transactions_wallet_id'), table_name='payslip_transactions')
    op.drop_table('payslip_transactions')
    op.drop_index(op.f('ix_payslip_forms_salon_id'), table_name='payslip_forms')
    op.drop_index(op.f('ix_payslip_forms_employee_id'), table_name='payslip_forms')
    op.drop_table('payslip_forms')
    op.drop_index(op.f('ix_monthly_salaries_monthly_report_id'), table_name='monthly_salaries')
    op.drop_index(op.f('ix_monthly_salaries_employee_id'), table_name='monthly_salaries')
    op.drop_table('monthly_salaries')
    op.drop_index(op.f('ix_monthly_primes_salon_id'), table_name='monthly_primes')
    op.drop_index(op.f('ix_monthly_primes_employee_id'), table_name='monthly_primes')
    op.drop_table('monthly_primes')
    op.drop_index(op.f('ix_expenses_monthly_report_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_services_salon_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_salon_config_salon_id'), table_name='salon_config')
    op.drop_table('salon_config')
    op.drop_index(op.f('ix_prime_config_salon_id'), table_name='prime_config')
    op.drop_table('prime_config')
    op.drop_table('payslip_wallet')
    op.drop_table('noly_subscriptions')
    op.drop_index(op.f('ix_monthly_reports_salon_id'), table_name='monthly_reports')
    op.drop_table('monthly_reports')
    op.drop_index(op.f('ix_employees_salon_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_coco_conversations_user_id'), table_name='coco_conversations')
    op.drop_index(op.f('ix_coco_conversations_salon_id'), table_name='coco_conversations')
    op.drop_table('coco_conversations')
    op.drop_index(op.f('ix_salons_user_id'), table_name='salons')
    op.drop_table('salons')
    op.drop_table('coco_user_profiles')
    op.drop_index(op.f('ix_blog_articles_slug'), table_name='blog_articles')
    op.drop_index(op.f('ix_blog_articles_author_id'), table_name='blog_articles')
    op.drop_table('blog_articles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_partners_category'), table_name='partners')
    op.drop_table('partners')
    op.drop_table('expense_categories')
    op.drop_table('admin_config')
    # ### end Alembic commands ###
